package com.zero.admin;

import com.fasterxml.jackson.core.type.TypeReference;
import com.zero.admin.vo.http.response.JuHeProductDateResponseVo;
import com.zero.admin.vo.http.response.JuHeReturnVo;
import com.zero.common.util.JsonHelper;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

/**
 * @author yezhaoxing
 * @date 2017/09/16
 */
@RunWith(SpringJUnit4ClassRunner.class)
public class StringHelperTest {

    @Test
    public void testJson() {
        TypeReference<JuHeReturnVo<JuHeProductDateResponseVo>> TYPE_REFERENCE = new TypeReference<JuHeReturnVo<JuHeProductDateResponseVo>>() {
        };
        String response = "{\n" +
                "\t\"resultcode\":\"200\",\n" +
                "\t\"reason\":\"Success\",\n" +
                "\t\"result\":{\n" +
                "\t\t\"data\":[\n" +
                "\t\t\t{\n" +
                "\t\t\t\t\"id\":\"130\",\n" +
                "\t\t\t\t\"title\":\"营养美味家常菜---豆豉烧鳕鱼\",\n" +
                "\t\t\t\t\"tags\":\"家常菜;10-20分钟;烧;香;全菜系;1-2人;锅子\",\n" +
                "\t\t\t\t\"imtro\":\"鳕鱼低脂肪，高蛋白，肉鲜美，刺少，是老少皆宜营养食品。 加入了豆豉，让鳕鱼味道更鲜美，还能去除腥味，是很好吃的一道营养美味家常菜。\",\n" +
                "\t\t\t\t\"ingredients\":\"鳕鱼,1条\",\n" +
                "\t\t\t\t\"burden\":\"葱,适量;蒜瓣,8粒;豆豉酱,30g;料酒,20ml;生抽,15ml;糖,5g;水淀粉,适量;鸡蛋液,适量;姜,适量\",\n" +
                "\t\t\t\t\"albums\":[\n" +
                "\t\t\t\t\t\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/t\\/1\\/130_685751.jpg\"\n" +
                "\t\t\t\t],\n" +
                "\t\t\t\t\"steps\":[\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/2\\/130_b6e4aa5e13c352f4.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"1.准备好所有的食材。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/2\\/130_4da781fa7d92d1ee.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"2.鳕鱼洗净切块，放入蛋液中裹均匀。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/2\\/130_70da9c628a2ac80e.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"3.不粘锅倒油放入裹蛋液的鳕鱼块煎至。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/2\\/130_1af8edcd3979f04d.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"4.中小火煎至两面微黄即好。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/2\\/130_91892ec485aa4bed.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"5.炒锅倒油爆香葱姜蒜。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/2\\/130_c2f631887653df7e.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"6.倒入豆豉炒出香味。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/2\\/130_8bbcf55d13713fdb.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"7.放入煎好的鳕鱼块。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/2\\/130_8ff67eec3913e4a6.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"8.加入料酒。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/2\\/130_ccc89017cc9ec3a7.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"9.再加糖和生抽。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/2\\/130_b1ccc0ea4e7f2a57.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"10.加入适量的清水大火炖煮。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/2\\/130_af287d5843c53241.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"11.煮至汤汁快干时，加入适量的水淀粉。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/2\\/130_8ad6af5210a97faf.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"12.翻炒均匀关火。\"\n" +
                "\t\t\t\t\t}\n" +
                "\t\t\t\t]\n" +
                "\t\t\t},\n" +
                "\t\t\t{\n" +
                "\t\t\t\t\"id\":\"399\",\n" +
                "\t\t\t\t\"title\":\"最经典的家常菜---土豆烧肉\",\n" +
                "\t\t\t\t\"tags\":\"家常菜;增肥;烧;香;冬季;2小时以上;1-2人;健脾;祛风散寒;祛寒;健脾胃;经典菜;锅子;儿子最喜欢;助睡眠;脾虚\",\n" +
                "\t\t\t\t\"imtro\":\"土豆烧肉很经典的家常菜。 也是百吃不厌的一道菜，大家都爱的下饭菜。\",\n" +
                "\t\t\t\t\"ingredients\":\"土豆,200g;猪肥瘦肉,250g\",\n" +
                "\t\t\t\t\"burden\":\"油,适量;盐,适量;葱姜,适量;大料,2个;桂皮,1小块;香叶,2片;老抽,5ml;生抽,15ml;红糖,10g;白糖,10g;香油,适量\",\n" +
                "\t\t\t\t\"albums\":[\n" +
                "\t\t\t\t\t\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/t\\/1\\/399_937531.jpg\"\n" +
                "\t\t\t\t],\n" +
                "\t\t\t\t\"steps\":[\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/4\\/399_d14918ae9d817edb.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"1.准备好所有的食材。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/4\\/399_896d825837cdbb8f.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"2.猪肉洗净切片，准备好所有的调味料。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/4\\/399_e3c45c987b31d5d0.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"3.炒锅倒油烧热倒入猪肉翻炒。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/4\\/399_dfa46567bea7da0d.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"4.翻炒至猪肉微黄。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/4\\/399_3fdd6761804e04ec.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"5.然后加入红白糖继续翻炒至猪肉上色。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/4\\/399_f99d67686a3fe219.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"6.加入所有调味料炒出香味。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/4\\/399_c595c142e547b38a.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"7.加入白酒炒香。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/4\\/399_987b42ea17c88ee0.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"8.加入老抽。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/4\\/399_357a77c1687273e1.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"9.在加入生抽。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/4\\/399_0fb8cd4e03b724e5.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"10.继续翻炒至猪肉上色。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/4\\/399_411f5f01dd1e9e9e.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"11.加入适量的清水。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/4\\/399_4fe7aadaf9fd3d7a.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"12.大火煮开后撇去浮沫。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/4\\/399_1e165a4a20590a6c.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"13.加盖小火焖至40分钟。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/4\\/399_c48ffca87ddd132b.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"14.40分钟后加入去皮切块的土豆中火烧至土豆软烂。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/4\\/399_f9942da1837efbff.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"15.加少许盐调味淋入香油。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/4\\/399_9c8a1a80d33af78f.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"16.大火收汁即好。\"\n" +
                "\t\t\t\t\t}\n" +
                "\t\t\t\t]\n" +
                "\t\t\t},\n" +
                "\t\t\t{\n" +
                "\t\t\t\t\"id\":\"765\",\n" +
                "\t\t\t\t\"title\":\"10分钟家常菜——香菇肉片\",\n" +
                "\t\t\t\t\"tags\":\"家常菜;瘦身;润肠通便;高血脂;防癌;咸香;10分钟内;动脉硬化;便秘;宴请;降血脂;减肥;提高免疫力;朋友聚餐;1-2人;健脾;肥胖;脂肪肝;健脾胃;锅子;其他工艺;脾虚\",\n" +
                "\t\t\t\t\"imtro\":\"香菇是文子家中的常备菌类，不但味道鲜美，而且对身体有很多好处哦！ 香菇素有\\\"山珍之王\\\"之称，是高蛋白、低脂肪的营养食品，能增强细胞免疫能力，香菇中的脂肪所含脂肪酸，有降血脂的作用。 这道菌类和肉类搭配的简单菜菜，会让你的饭饭美味不少哦！\",\n" +
                "\t\t\t\t\"ingredients\":\"肉片,150g;香菇,200g\",\n" +
                "\t\t\t\t\"burden\":\"油,适量;盐,适量;香菜,适量;姜,适量;蒜,适量;鸡粉,适量\",\n" +
                "\t\t\t\t\"albums\":[\n" +
                "\t\t\t\t\t\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/t\\/1\\/765_194904.jpg\"\n" +
                "\t\t\t\t],\n" +
                "\t\t\t\t\"steps\":[\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/765_83eb105f05a9ae61.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"1.肉片解冻。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/765_073c43dead038883.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"2.香菇洗净、去蒂、切片。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/765_c610b7d80071ace2.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"3.准备好香菜碎碎、蒜末和姜末\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/765_e74e40bdcc0c8520.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"4.解冻的肉片中加入葱姜、老抽，搅拌均匀，稍稍腌制一会儿。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/765_2e43de42fea3ab91.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"5.热油，加入腌好的肉片，翻炒至肉片断生。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/765_3aacad662beb9662.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"6.加入香菇片，继续翻炒至香菇渗出汁水来，煮一会儿。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/765_2313f81a744f0a2a.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"7.加入水淀粉，收汁。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/765_124e17cbc84cbf0f.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"8.出锅前加入盐、鸡粉、少许香菜调味，鲜香美味的香菇肉片就得了！\"\n" +
                "\t\t\t\t\t}\n" +
                "\t\t\t\t]\n" +
                "\t\t\t},\n" +
                "\t\t\t{\n" +
                "\t\t\t\t\"id\":\"784\",\n" +
                "\t\t\t\t\"title\":\"10分钟家常菜——芹菜熘肉片\",\n" +
                "\t\t\t\t\"tags\":\"家常菜;瘦身;排毒;高血压;10分钟内;解酒;便秘;宴请;冬季;降血压;解暑;下火;美白;减肥;去火;清火;朋友聚餐;1-2人;清热解暑;肥胖;清热下火;祛痘;脂肪肝;锅子;其他工艺;祛痘美白;阳盛质\",\n" +
                "\t\t\t\t\"imtro\":\"香芹不但美味，而且有不错的食疗作用，要不怎么又叫“药芹”呢！ 芹菜的功效有：清热除烦，平肝，利水消肿，凉血止血。主治高血压，头痛，头晕，暴热烦渴，黄疸，水肿，小便热涩不利等，女性同志经常食用芹菜，能调理月经不调，赤白带下等病症。 文子喜欢细细的小芹菜，在这个季节，家中冰箱常备一捆这青翠青翠的小芹菜。 芹菜叶子和芹菜茎往往用来配不同的食材炒。 芹菜茎脆脆的，配上鲜美的猪肉，口味颇佳哦~\",\n" +
                "\t\t\t\t\"ingredients\":\"猪肉片,200g;芹菜,200g\",\n" +
                "\t\t\t\t\"burden\":\"油,适量;盐,适量;蒜,适量;姜,适量;老抽,适量;海鲜酱油,适量;白糖,适量\",\n" +
                "\t\t\t\t\"albums\":[\n" +
                "\t\t\t\t\t\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/t\\/1\\/784_878406.jpg\"\n" +
                "\t\t\t\t],\n" +
                "\t\t\t\t\"steps\":[\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/784_6d32a27a917da9a1.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"1.猪肉切片。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/784_161ea85a79a50481.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"2.准备好姜与蒜。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/784_45635f9324ea4431.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"3.在猪肉片中加入适量老抽、海鲜酱油、姜、蒜，搅拌均匀。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/784_299879d1f17f7425.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"4.再加入干淀粉搅拌均匀，放置待用。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/784_79771db9be535550.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"5.芹菜切成小段。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/784_bf0a9e77ed1bd651.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"6.稍多的油熘肉片至猪肉变色。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/784_79d88f9526de1aa2.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"7.加入芹菜，大火翻炒2分钟左右。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/784_b64689afe1728967.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"8.根据菜已有的咸度，加入适量白糖、盐翻炒均匀，即可装盘。\"\n" +
                "\t\t\t\t\t}\n" +
                "\t\t\t\t]\n" +
                "\t\t\t},\n" +
                "\t\t\t{\n" +
                "\t\t\t\t\"id\":\"789\",\n" +
                "\t\t\t\t\"title\":\"家常菜之西红柿炒鸡蛋\",\n" +
                "\t\t\t\t\"tags\":\"家常菜;美容;延缓衰老;防辐射;防癌;抗癌;10-20分钟;炒;孕妇;青少年;老人;白领;消化不良;晚餐;营养;开胃;增强抵抗力;抗衰老;抗氧化;补铁;促消化;全菜系;1-2人;防晒;凉血;清热解暑;待客菜;番茄味;炒锅;缓解压力\",\n" +
                "\t\t\t\t\"imtro\":\"我问儿子，最喜欢吃什么菜，他说是西红柿炒鸡蛋，这道菜虽然做法简单，味道却老少皆宜，不失为一道经典的家常菜 成本核算： 西红柿一个0.5元 鸡蛋2个1.50元 =========== 合计2元\",\n" +
                "\t\t\t\t\"ingredients\":\"西红柿,50g;鸡蛋,2个\",\n" +
                "\t\t\t\t\"burden\":\"盐,2g;鸡精,1g;葱花,1g;糖,2g\",\n" +
                "\t\t\t\t\"albums\":[\n" +
                "\t\t\t\t\t\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/t\\/1\\/789_903595.jpg\"\n" +
                "\t\t\t\t],\n" +
                "\t\t\t\t\"steps\":[\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/789_f4966dda4ede793e.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"1.鸡蛋打成液加少许盐，鸡精拌匀，不粘锅烧热放入适量橄榄油，放入蛋液\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/789_a269b807ca417dac.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"2.待其凝固，用筷子搅拌碎，盛出来\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/789_9721cf393081364d.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"3.锅内底油，放入西红柿翻炒，加盐和糖炒至西红柿软身\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/789_da5512abbf5c5f69.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"4.放入鸡蛋碎，翻炒出锅\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/789_20227efbd17097cb.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"5.成品，撒上葱花上桌\"\n" +
                "\t\t\t\t\t}\n" +
                "\t\t\t\t]\n" +
                "\t\t\t},\n" +
                "\t\t\t{\n" +
                "\t\t\t\t\"id\":\"795\",\n" +
                "\t\t\t\t\"title\":\"豆角煎蛋--经典家常菜\",\n" +
                "\t\t\t\t\"tags\":\"家常菜;夏季饮食\",\n" +
                "\t\t\t\t\"imtro\":\"豆角煎蛋是十分老式的菜了，此菜咸香味，取料容易，操作简单，群众喜闻乐吃，有蛋有菜，老少大中咸宜。\",\n" +
                "\t\t\t\t\"ingredients\":\"豆角,200g;鸡蛋,2个\",\n" +
                "\t\t\t\t\"burden\":\"油,适量;盐,适量;胡椒粉,适量\",\n" +
                "\t\t\t\t\"albums\":[\n" +
                "\t\t\t\t\t\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/t\\/1\\/795_540859.jpg\"\n" +
                "\t\t\t\t],\n" +
                "\t\t\t\t\"steps\":[\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/795_6d42c409b6e4c444.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"1.将豆角切粒、蛋打散，放盐1\\/2茶匙、胡椒粉1\\/2茶匙、用叉子打均匀，放水1汤匙，打均匀，沙拉油1汤匙，再打均匀；\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/795_cc7f540c8c89d015.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"2.豆角在锅里炒至八成熟，炒时放少许盐；\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/795_10355ffd0b9d0c1a.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"3.将炒好的豆角倒入蛋液里，搅拌均匀；\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/795_156b35183769de17.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"4.在平底锅里摊平来煎，中火，锅较小的分次煎，不宜过厚；\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/8\\/795_255b77e47b3aabb8.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"5.煎好一面用稍宽的锅铲铲起来，反转面再煎成金黄色，如图。\"\n" +
                "\t\t\t\t\t}\n" +
                "\t\t\t\t]\n" +
                "\t\t\t},\n" +
                "\t\t\t{\n" +
                "\t\t\t\t\"id\":\"805\",\n" +
                "\t\t\t\t\"title\":\"家常菜里最好吃的肉菜配【排骨炖小土豆】\",\n" +
                "\t\t\t\t\"tags\":\"家常菜;增肥;半小时-1小时;炖;香;孕妇;青少年;老人;白领;晚餐;冬季;营养;增强抵抗力;全菜系;1-2人;健脾;待客菜;祛风散寒;祛寒;健脾胃;锅子;助睡眠;脾虚\",\n" +
                "\t\t\t\t\"imtro\":\"前段时间炖了一锅五花肉和小土豆，超级好吃，今天这道排骨炖小土豆和五花肉炖的方法差不多，排骨炖的肉肉酥烂，土豆软糯，味道那肯定也是一样的好吃没话说。\",\n" +
                "\t\t\t\t\"ingredients\":\"排骨,800g;土豆,500g\",\n" +
                "\t\t\t\t\"burden\":\"油,适量;盐,适量;红椒干,适量;八角,适量;香叶,适量;料酒,适量;冰糖,适量;红烧汁,适量;腐乳汁,适量;枸杞,适量;草果,适量;花椒,适量\",\n" +
                "\t\t\t\t\"albums\":[\n" +
                "\t\t\t\t\t\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/t\\/1\\/805_100770.jpg\"\n" +
                "\t\t\t\t],\n" +
                "\t\t\t\t\"steps\":[\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/9\\/805_6c52c00f72b7d352.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"1.将小土豆去皮\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/9\\/805_7fa93781dc586cca.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"2.排骨倒入冷水锅内大火烧开氽烫去除杂质\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/9\\/805_80646840ebbf9def.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"3.氽烫好的排骨捞出沥干备用\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/9\\/805_97c7665be53b0274.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"4.锅内倒油后放入冰糖熬糖色，熬至冰糖冰金黄即可\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/9\\/805_f01b3fde5213b49b.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"5.将沥干水的排骨倒入锅内\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/9\\/805_1a7a0d15344b2c7a.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"6.快炒后上色\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/9\\/805_1a4bca7d8cf46110.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"7.将红烧汁，料酒，腐乳汁和少许醋倒入翻炒\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/9\\/805_c605808c4630fee9.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"8.加入小土豆\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/9\\/805_a1b548f69f614149.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"9.翻炒至土豆沾上汤汁\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/9\\/805_f8e13491eabe2827.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"10.加入草果，香叶，红椒枸杞蒜头等配料\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/9\\/805_26a7d7601f115d10.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"11.加所有食材盛至煲内\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/9\\/805_25ca31a3c2b241e3.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"12.加入水漫至煲的最高位， 小火将煲内食材煮沸， 煮至汤汁收至一半后即可关火\"\n" +
                "\t\t\t\t\t}\n" +
                "\t\t\t\t]\n" +
                "\t\t\t},\n" +
                "\t\t\t{\n" +
                "\t\t\t\t\"id\":\"892\",\n" +
                "\t\t\t\t\"title\":\"家常菜红烧茄子\",\n" +
                "\t\t\t\t\"tags\":\"家常菜;夏季;红烧;川妈\",\n" +
                "\t\t\t\t\"imtro\":\"茄子是我喜欢的食物之一，做法也多，可以炒，可以蒸，可以炒肉，也可以焖蛋饼，每一样都是我喜欢的。 今天我要说的，是我喜欢的做法之一，也是最喜欢的吃的一种啊。\",\n" +
                "\t\t\t\t\"ingredients\":\"茄子,450g;肥猪肉,50g\",\n" +
                "\t\t\t\t\"burden\":\"油,适量;盐,适量;蒜头,4个;豆鼓,20g\",\n" +
                "\t\t\t\t\"albums\":[\n" +
                "\t\t\t\t\t\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/t\\/1\\/892_287688.jpg\"\n" +
                "\t\t\t\t],\n" +
                "\t\t\t\t\"steps\":[\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/9\\/892_d5cc8ab16c998cf1.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"1.买二个茄子，洗净，切好，然后放在水里泡一泡，说这样可以去掉茄子的毒。 我这是泡过的茄子，装起来滤下水。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/9\\/892_aa3da8b54feb7c6d.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"2.对半切，在有皮的一面，用刀打斜切成如下面相片所示的样子。 看图说话，最明白啊。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/9\\/892_5a92c61677cae87e.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"3.准备一点蒜，拍一拍就行了。 我还切了点肥肉，嘻嘻，这肥肉煎点油，香啊\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/9\\/892_3e6108fd4b6d3bf5.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"4.放油，把猪肉放进去稍煎下，别煎太干了，煎茄子时，猪肉还被煎的。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/9\\/892_d125bfa96ffa3681.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"5.把茄子放入锅，一块一块分别贴着锅里，煎不带皮的那边。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/9\\/892_837060c2bce87348.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"6.看茄子在变色，变软，猪肉的油在不停得煎出来，这样不会油少，烧锅啊。 用锅驼机铲按一按，觉得茄子有点软了，换煎另一边。 要及时变换火的大小，不要煎过火了。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/9\\/892_69652254f02651f9.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"7.二边煎软了，放入蒜头，放一点生抽，放一点豆鼓，翻一翻啊。 再加入少许水，把茄子完全的煮软，煮透，这样才好吃啊。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/9\\/892_2be93f9212899b98.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"8.来了，做好，上桌了，感觉怎么样啊？ 吃起来，还真是香啊，嘻嘻，又下饭又开胃啊，真是好吃。\"\n" +
                "\t\t\t\t\t}\n" +
                "\t\t\t\t]\n" +
                "\t\t\t},\n" +
                "\t\t\t{\n" +
                "\t\t\t\t\"id\":\"929\",\n" +
                "\t\t\t\t\"title\":\"香辣镇江肉排——美味家常菜\",\n" +
                "\t\t\t\t\"tags\":\"家常菜;酸辣;香辣;秋季菜谱;生津\",\n" +
                "\t\t\t\t\"imtro\":\"用镇江骨汁做镇江肉排，加了些青辣椒，味道酸甜香辣非常开胃好吃。有时候自己想：其实，做菜犹如做人，要想知道自己能否做好某件事，就得大胆的去尝试，如果只想不做，不去尝试，那么，我们永远都不会知道事情的结果如何？今天，分享的这款“香辣镇江肉排”就是在简单的烹饪之后加了些青辣椒，吃起来真的非常美味，盘里的酱汁有点不留！\",\n" +
                "\t\t\t\t\"ingredients\":\"排骨,500g;青辣椒,100g;洋葱,70g\",\n" +
                "\t\t\t\t\"burden\":\"油,适量;糖,适量;镇江骨汁,适量;生抽,适量;姜葱,适量\",\n" +
                "\t\t\t\t\"albums\":[\n" +
                "\t\t\t\t\t\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/t\\/1\\/929_914841.jpg\"\n" +
                "\t\t\t\t],\n" +
                "\t\t\t\t\"steps\":[\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/10\\/929_85952daf21633a5d.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"1.买回来的排骨清洗干净。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/10\\/929_f8b0cb8057922469.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"2.按骨头排列切块，然后用生抽腌制片刻。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/10\\/929_924272af03227a23.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"3.不粘锅热油然后将排骨放入煎至两面金黄。（也可以用炸的方法）\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/10\\/929_d098051faaddb6c1.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"4.煎好的排骨。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/10\\/929_ee2ea03e84d0e2bf.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"5.放三碗水，香葱和姜一起将煎好的排骨大火烧开直至排骨酥烂即将收汁时将香葱捞起弃之。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/10\\/929_2f86b702e9d74719.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"6.准备镇江骨汁。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/10\\/929_45b0ca267aba25ce.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"7.在排骨烧直酥烂差不多收汁时倒入半碗镇江骨汁，加少许糖大火烧至收汁。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/10\\/929_b4a4e7238c8cb5cd.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"8.准备青辣椒洋葱和大蒜。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/10\\/929_c21dae0c36c2b94a.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"9.将青辣椒和洋葱大蒜放入烧好的排骨里。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/10\\/929_f0c993b065959634.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"10.快速翻炒让辣椒和洋葱均匀裹上镇江骨汁。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/10\\/929_c982d888db936d95.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"11.炒好的“香辣镇江肉排”酸甜香辣，酥烂美味！是下饭下酒的家庭美食！\"\n" +
                "\t\t\t\t\t}\n" +
                "\t\t\t\t]\n" +
                "\t\t\t},\n" +
                "\t\t\t{\n" +
                "\t\t\t\t\"id\":\"973\",\n" +
                "\t\t\t\t\"title\":\"家常菜--肉末什锦小炒\",\n" +
                "\t\t\t\t\"tags\":\"家常菜;咸香;10-20分钟;炒;孕妇;青少年;老人;白领;晚餐;营养;增强抵抗力;补铁;全菜系;3-4人;补中益气;待客菜;炒锅\",\n" +
                "\t\t\t\t\"imtro\":\"肉末什锦小炒--咸鲜口味。\",\n" +
                "\t\t\t\t\"ingredients\":\"猪肉,200g;洋葱,100g;青椒,1个;红椒,1个\",\n" +
                "\t\t\t\t\"burden\":\"葱,10g;姜,5g;蒜,适量;八角,适量;花生油,25ml;盐,2g;料酒,10ml;酱油,15ml;白糖,20g;醋,20ml;味精,2g\",\n" +
                "\t\t\t\t\"albums\":[\n" +
                "\t\t\t\t\t\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/t\\/1\\/973_270975.jpg\"\n" +
                "\t\t\t\t],\n" +
                "\t\t\t\t\"steps\":[\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/10\\/973_3be6803bc05d47fb.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"1.先把猪肉切成小丁。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/10\\/973_d2541affae00341a.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"2.青红椒洗净，洋葱剥掉外皮。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/10\\/973_96870d71c0bf2f26.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"3.将洋葱、青红椒切成小块。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/10\\/973_29f456ca7d6f657e.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"4.葱、姜、蒜切碎。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/10\\/973_28e75d7a2fba6ffc.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"5.锅里放油，先放入八角煸炒。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/10\\/973_549b7f0b79db2dac.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"6.放入肉丁炒至变色。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/10\\/973_bad2cc184c01a87b.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"7.放入葱、姜、蒜煸炒。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/10\\/973_d9a880757826ebe7.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"8.添加料酒、酱油、白糖、醋翻炒。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/10\\/973_584bb24e27047b81.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"9.放入青红椒、洋葱翻炒。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/10\\/973_bf07eb11adcdbf0a.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"10.放入盐、味精调味即可。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/10\\/973_061c2e71eba39f56.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"11.出锅装盘，即可享用。\"\n" +
                "\t\t\t\t\t}\n" +
                "\t\t\t\t]\n" +
                "\t\t\t},\n" +
                "\t\t\t{\n" +
                "\t\t\t\t\"id\":\"1288\",\n" +
                "\t\t\t\t\"title\":\"家常菜豆腐\",\n" +
                "\t\t\t\t\"tags\":\"家常菜;美容;通乳;增肥;痰湿质;骨质疏松;白领;止咳;补钙;快手菜;咳嗽;农家菜;化痰;催乳;止咳化痰;下奶;小儿咳嗽\",\n" +
                "\t\t\t\t\"imtro\":\"在万能的好豆上学的菜谱，当然也稍微改良了下。好下饭的菜品，以后会成为我家饭桌的常客的。有菜，有豆腐，有肉末，完满了。\",\n" +
                "\t\t\t\t\"ingredients\":\"豆腐,200g;肉末,150g;油麦菜,100g\",\n" +
                "\t\t\t\t\"burden\":\"油,适量;盐,适量;鸡精,适量;蒜末,适量\",\n" +
                "\t\t\t\t\"albums\":[\n" +
                "\t\t\t\t\t\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/t\\/2\\/1288_804672.jpg\"\n" +
                "\t\t\t\t],\n" +
                "\t\t\t\t\"steps\":[\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/13\\/1288_e5c7acf5ab909982.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"1.准备好食材：豆腐+肉末+蒜末+油麦菜（可以根据自己的喜好选择各类有叶子的蔬菜）\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/13\\/1288_150ab7e5b57a655a.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"2.豆腐用手捏碎\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/13\\/1288_d47d66d098b34d45.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"3.油麦菜洗净，剁成菜碎\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/13\\/1288_0a5a44b9cdc06619.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"4.锅内下油，烧热，下蒜末煸炒出香味\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/13\\/1288_bd80064b9fa60d85.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"5.下肉末煸炒\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/13\\/1288_b29a945d535afe76.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"6.至肉末颜色变白，下豆腐碎，翻炒均匀\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/13\\/1288_46d70b88ebc222e4.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"7.至煮出一点点汤，下适量的鸡精和盐调味\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/13\\/1288_56bd4ea311d8cd8f.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"8.下剁碎的菜，煮到菜熟，即可出锅\"\n" +
                "\t\t\t\t\t}\n" +
                "\t\t\t\t]\n" +
                "\t\t\t},\n" +
                "\t\t\t{\n" +
                "\t\t\t\t\"id\":\"10212\",\n" +
                "\t\t\t\t\"title\":\"【家常菜】韭菜炒鸡蛋\",\n" +
                "\t\t\t\t\"tags\":\"家常菜;瘦身;护肝;排毒;阳虚质;10分钟内;炒;便秘;春季;减肥;补铁;杀菌;朋友聚餐;1-2人;肥胖;尿频;抗菌;壮阳;养肝护肝;补肝;炒锅;回奶;阳痿\",\n" +
                "\t\t\t\t\"imtro\":\"鸡蛋作为餐桌必备食物，其实做法挺多的。不过感觉与韭菜的搭配真是绝配啊。不但但口感好，颜色也超棒哦。加上制作有非常简单。所以，很受妈妈和小朋友的欢迎哦。\",\n" +
                "\t\t\t\t\"ingredients\":\"鸡蛋,2个;韭菜,50g\",\n" +
                "\t\t\t\t\"burden\":\"油,适量;盐,适量;味精,适量\",\n" +
                "\t\t\t\t\"albums\":[\n" +
                "\t\t\t\t\t\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/t\\/11\\/10212_405857.jpg\"\n" +
                "\t\t\t\t],\n" +
                "\t\t\t\t\"steps\":[\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/103\\/10212_1f0e6c4fe2462ce0.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"1.这是原材料，很普通哦\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/103\\/10212_2aa7c0c3b13ff880.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"2.就爱那个韭菜切成1cm长的段，鸡蛋加入少了胡萝卜丝儿打散备用\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/103\\/10212_a0c5ff1895e04d95.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"3.热锅冷油，先将鸡蛋放入像摊煎饼一样摊个鸡蛋饼\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/103\\/10212_7ea30d4ee956d13f.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"4.反面煎熟\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/103\\/10212_6a2adbe973868535.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"5.快速切成大块\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/103\\/10212_9e932f2bb56b7ac5.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"6.装出备用\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/103\\/10212_518ebfe6a76c91cd.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"7.利用锅里的底油，将韭菜快速翻炒一下，并加入调味料调味，将炒好的鸡蛋倒入翻搅均匀即可\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/103\\/10212_41ea5aca733a9f64.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"8.装盘就可以吃了。很棒吧！\"\n" +
                "\t\t\t\t\t}\n" +
                "\t\t\t\t]\n" +
                "\t\t\t},\n" +
                "\t\t\t{\n" +
                "\t\t\t\t\"id\":\"15227\",\n" +
                "\t\t\t\t\"title\":\"红烧排骨冻豆腐——家常菜\",\n" +
                "\t\t\t\t\"tags\":\"冬季;夏季饮食;养心安神;健脾除湿\",\n" +
                "\t\t\t\t\"imtro\":\"家里每一次买豆腐都是一大桶，需要天天换水，我喜欢将一部分马上吃，另外一部分放入雪柜冰冻起来，因为，冰冻的水豆腐含有丰富的卵磷脂、不饱和脂肪酸和膳食纤维，有降低胆固醇和防止动脉粥样硬化的效果。 今天晚餐用冻豆腐，排骨和胡萝卜烧了一款菜，营养搭配不错，而且也很下饭。当然，在我们家，晚餐提倡只吃7成饱，再好吃的菜也不能贪吃，身体健康最重要！哈哈\",\n" +
                "\t\t\t\t\"ingredients\":\"排骨,250g;冻豆腐,200g;胡萝卜,100g\",\n" +
                "\t\t\t\t\"burden\":\"油,两汤匙;生抽,两汤匙\",\n" +
                "\t\t\t\t\"albums\":[\n" +
                "\t\t\t\t\t\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/t\\/16\\/15227_809256.jpg\"\n" +
                "\t\t\t\t],\n" +
                "\t\t\t\t\"steps\":[\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/153\\/15227_de072d56a4ac623f.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"1.买回来的排骨切块然后用生抽，料酒腌制。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/153\\/15227_a9524e7dd96cb767.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"2.准备冻豆腐和胡萝卜。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/153\\/15227_b78cc29c2029f68c.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"3.煮锅放入少许油然后将排骨放入炒香。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/153\\/15227_f098d05ff3cf2213.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"4.加少许水放入炒香的排骨里中火焖煮二十几分钟。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/153\\/15227_3e65db76fb452569.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"5.将排骨煮得比较酥软时放入冻豆腐和胡萝卜。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/153\\/15227_3002b957a017dcaf.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"6.放少许老抽上色加点生抽调料大火烧开然后改中火焖煮十分钟。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/153\\/15227_26aaf871b92c15fc.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"7.出锅前大火烧至收汁即可。\"\n" +
                "\t\t\t\t\t},\n" +
                "\t\t\t\t\t{\n" +
                "\t\t\t\t\t\t\"img\":\"http:\\/\\/juheimg.oss-cn-hangzhou.aliyuncs.com\\/cookbook\\/s\\/153\\/15227_7f588934021a30f6.jpg\",\n" +
                "\t\t\t\t\t\t\"step\":\"8.烧好的“排骨红烧冻豆腐”。排骨肉质酥烂，冻豆腐软而有劲，胡萝卜甘甜清香。这款家常菜最适合上班族做一次吃两餐了。\"\n" +
                "\t\t\t\t\t}\n" +
                "\t\t\t\t]\n" +
                "\t\t\t}\n" +
                "\t\t],\n" +
                "\t\t\"totalNum\":\"54\",\n" +
                "\t\t\"pn\":0,\n" +
                "\t\t\"rn\":30\n" +
                "\t},\n" +
                "\t\"error_code\":0\n" +
                "}";
        JuHeReturnVo<JuHeProductDateResponseVo> returnVo = JsonHelper.readValue(response, TYPE_REFERENCE);
        JuHeProductDateResponseVo result = returnVo.getResult();
    }
}
